name: tajdeed_pro_mag
description: A clean, minimalist Flutter WebView app for Tajdeed Pro Magazine.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2c2c2c"
  adaptive_icon_foreground: "assets/icon/icon.png"
